"""add missing achievements tables

Revision ID: c3db1f1fdb1f
Revises: 0005_add_custom_frequency_and_schedule
Create Date: 2026-04-29 23:04:59.056585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3db1f1fdb1f'
down_revision = '0005_add_custom_frequency_and_schedule'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('xp_bonus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_key'), ['key'], unique=True)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    if op.get_bind().dialect.name != "sqlite":
        with op.batch_alter_table('categorias', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('categorias_nombre_key'), type_='unique')
            batch_op.drop_index(batch_op.f('idx_categorias_nombre'))
            batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

        with op.batch_alter_table('habitos', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_habitos_categoria'))
            batch_op.create_index(batch_op.f('ix_habitos_categoria_id'), ['categoria_id'], unique=False)

        with op.batch_alter_table('habitos_usuario', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_habitos_usuario_habito'))
            batch_op.drop_index(batch_op.f('idx_habitos_usuario_usuario'))
            batch_op.create_index(batch_op.f('ix_habitos_usuario_habito_id'), ['habito_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_habitos_usuario_usuario_id'), ['usuario_id'], unique=False)

        with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_pomodoro_sessions_user_started'))
            batch_op.create_index(batch_op.f('ix_pomodoro_sessions_user_id'), ['user_id'], unique=False)

        with op.batch_alter_table('registro_habitos', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_registro_fecha'))
            batch_op.create_index(batch_op.f('ix_registro_habitos_habitousuario_id'), ['habitousuario_id'], unique=False)

        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_users_email'))
            batch_op.drop_index(batch_op.f('idx_users_username'))

        with op.batch_alter_table('validaciones', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_validaciones_habitousuario'))
            batch_op.create_index(batch_op.f('ix_validaciones_habitousuario_id'), ['habitousuario_id'], unique=False)

        with op.batch_alter_table('xp_logs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_xp_logs_usuario'))
            batch_op.create_index(batch_op.f('ix_xp_logs_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != "sqlite":
        with op.batch_alter_table('xp_logs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_xp_logs_usuario_id'))
            batch_op.create_index(batch_op.f('idx_xp_logs_usuario'), ['usuario_id'], unique=False)

        with op.batch_alter_table('validaciones', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_validaciones_habitousuario_id'))
            batch_op.create_index(batch_op.f('idx_validaciones_habitousuario'), ['habitousuario_id'], unique=False)

        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
            batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

        with op.batch_alter_table('registro_habitos', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_registro_habitos_habitousuario_id'))
            batch_op.create_index(batch_op.f('idx_registro_fecha'), ['fecha'], unique=False)

        with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_user_id'))
            batch_op.create_index(batch_op.f('idx_pomodoro_sessions_user_started'), ['user_id', 'started_at'], unique=False)

        with op.batch_alter_table('habitos_usuario', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_habitos_usuario_usuario_id'))
            batch_op.drop_index(batch_op.f('ix_habitos_usuario_habito_id'))
            batch_op.create_index(batch_op.f('idx_habitos_usuario_usuario'), ['usuario_id'], unique=False)
            batch_op.create_index(batch_op.f('idx_habitos_usuario_habito'), ['habito_id'], unique=False)

        with op.batch_alter_table('habitos', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_habitos_categoria_id'))
            batch_op.create_index(batch_op.f('idx_habitos_categoria'), ['categoria_id'], unique=False)

        with op.batch_alter_table('categorias', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_categorias_nombre'))
            batch_op.create_index(batch_op.f('idx_categorias_nombre'), ['nombre'], unique=False)
            batch_op.create_unique_constraint(batch_op.f('categorias_nombre_key'), ['nombre'], postgresql_nulls_not_distinct=False)

        with op.batch_alter_table('user_achievements', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))

        op.drop_table('user_achievements')
        with op.batch_alter_table('achievements', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_achievements_key'))

        op.drop_table('achievements')
    else:
        op.drop_table('user_achievements')
        op.drop_table('achievements')
    # ### end Alembic commands ###
