"""add achievements tables

Revision ID: e60103f7d644
Revises: 0004_make_progress_validation_driven
Create Date: 2026-04-15 23:05:16.116340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60103f7d644'
down_revision = '0004_make_progress_validation_driven'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Preserve the legacy levels table; later code still reads/imports it.
    # The autogenerated migration tried to drop it, but that breaks the
    # expected schema on clean SQLite upgrades.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: keep `niveles` intact for downgrade symmetry.
    pass
    # ### end Alembic commands ###
